version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2
  browser-tools: circleci/browser-tools@1.1

jobs:
  test:  # our next job, called "test"
    docker:
      - image: cimg/ruby:2.7-browsers # this is our primary docker image, where step commands run.
      - image: circleci/postgres:9.5-alpine
        environment: # add POSTGRES environment variables.
          POSTGRES_USER: circleci
          POSTGRES_DB: jingle_jam_test
          POSTGRES_PASSWORD: ""
    # environment variables specific to Ruby/Rails, applied to the primary container.
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      CI: true
      FROM_EMAIL_ADDRESS: "jingle-jam@example.com"
      HMAC_SECRET: "c360bcae-df63-4616-808a-860f03d7da6b"
      PGHOST: 127.0.0.1
      PGPASSWORD: ""
      PGUSER: circleci
      RAILS_ENV: test
    # A series of steps to run, some are similar to those in "build".
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      # Here we make sure that the secondary container boots
      # up before we run operations on the database.
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Cucumber
          command: bundle exec cucumber

workflows:
  version: 2
  build_and_test:     # The name of our workflow is "build_and_test"
    jobs:             # The list of jobs we run as part of this workflow.
      - test          # Then run test,
